#!/usr/bin/env bash
VIRTUALDIRECTORY="./venv"

# ACTIVATE VENV
#echo "Excecuting \"source $VIRTUALDIRECTORY/bin/activate\""
source $VIRTUALDIRECTORY/bin/activate

# RUN PYTHON FILE
#echo "Running python compiler"
python src/compileLittle.py $1



