#!/usr/bin/env bash
VIRTUALDIRECTORY="./venv3"

# ACTIVATE VENV
#echo "Excecuting \"source $VIRTUALDIRECTORY/bin/activate\""
source $VIRTUALDIRECTORY/bin/activate

# RUN PYTHON FILE
#echo "Running python compiler"
python compileLittle.py $1



